


import java.sql.*;
import javax.swing.table.*;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aarav
 */
public class ProductsTabJframe extends javax.swing.JFrame {

    /**
     * Creates new form ProductsTabJframe
     */
    public ProductsTabJframe() {
        initComponents();
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProductCode = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        lblBusinessUnit = new javax.swing.JLabel();
        textFldProductCode = new javax.swing.JTextField();
        textFldProductName = new javax.swing.JTextField();
        textFldBusinessUnit = new javax.swing.JTextField();
        jButtonADD = new javax.swing.JButton();
        jButtonUPDATE = new javax.swing.JButton();
        jButtonDELETE = new javax.swing.JButton();
        jButtonCLEAR = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProductCode.setText("Product Code");

        lblProductName.setText("Product Name");

        lblBusinessUnit.setText("Business Unit");

        jButtonADD.setText("Add");
        jButtonADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDActionPerformed(evt);
            }
        });

        jButtonUPDATE.setText("Update");
        jButtonUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUPDATEActionPerformed(evt);
            }
        });

        jButtonDELETE.setText("Delete");
        jButtonDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDELETEActionPerformed(evt);
            }
        });

        jButtonCLEAR.setText("Clear");
        jButtonCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLEARActionPerformed(evt);
            }
        });

        jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Code", "Product Name", "Business Unit"
            }
        ));
        jt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt);

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblProductCode)
                                    .addComponent(lblProductName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBusinessUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFldBusinessUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFldProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonCLEAR)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButtonADD)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUPDATE)
                        .addGap(39, 39, 39)
                        .addComponent(jButtonDELETE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBack)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBack)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFldProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductCode))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProductName)
                            .addComponent(textFldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBusinessUnit)
                            .addComponent(textFldBusinessUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(jButtonCLEAR))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonADD)
                    .addComponent(jButtonUPDATE)
                    .addComponent(jButtonDELETE))
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDActionPerformed
        addData();
       showData();
    }//GEN-LAST:event_jButtonADDActionPerformed

    private void jButtonCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLEARActionPerformed
    clearData();
    }//GEN-LAST:event_jButtonCLEARActionPerformed

    private void jButtonUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUPDATEActionPerformed
        updateData();
        showData();
    }//GEN-LAST:event_jButtonUPDATEActionPerformed

    private void jButtonDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDELETEActionPerformed
        deleteData();
        showData();
        clearData();
    }//GEN-LAST:event_jButtonDELETEActionPerformed

    private void jtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMouseClicked
        showTableData();
    }//GEN-LAST:event_jtMouseClicked

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new HomePage().setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductsTabJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductsTabJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductsTabJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductsTabJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductsTabJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonADD;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCLEAR;
    private javax.swing.JButton jButtonDELETE;
    private javax.swing.JButton jButtonUPDATE;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jt;
    private javax.swing.JLabel lblBusinessUnit;
    private javax.swing.JLabel lblProductCode;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JTextField textFldBusinessUnit;
    private javax.swing.JTextField textFldProductCode;
    private javax.swing.JTextField textFldProductName;
    // End of variables declaration//GEN-END:variables

public void addData() {
    String productCode = textFldProductCode.getText();    //*declare and initialize customer variables
    String productName = textFldProductName.getText();          // and store text fields user inputs
    String businessUnit = textFldBusinessUnit.getText();
    
        
        
         try  (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/salesreporting","root","Tulip");  
        Statement stmt=con.createStatement();)
  { 
       
       String sql = "insert into products(product_code, product_name, business_unit)values('"+productCode+"', '"+productName+"', '"+businessUnit+"')";
               
        stmt.executeUpdate(sql);
        //con.commit();
        con.close();
        if(con != null) {
            System.out.println("Connection established and tabl created.");
        }
            }
         
  catch(Exception ex) {
      System.out.println("Connection unsuccessful");
      ex.printStackTrace();
    }
  }

public void showData() { 
   
    
       try  
  { 
        //Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/salesreporting","root","Tulip");  
        //Statement stmt=con.createStatement(); 
        
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/salesreporting","root","Tulip");  
        Statement stmt=con.createStatement();
       String sql = "select * from products order by product_id desc";
        ResultSet rs = stmt.executeQuery(sql);
        DefaultTableModel  model = (DefaultTableModel)jt.getModel();
        model.setRowCount(0);
        while(rs.next()) {
            
           
            String productCode = rs.getString(2);  
            String productName = rs.getString(3);
            String businessUnit = rs.getString(4);
           
            model.addRow(new Object[]{productCode, productName, businessUnit});
            
            
            
        }
        
        con.close();
        
        if(con != null) {
            System.out.println("Connection established and table created.");
        }
            } 
  catch(Exception ex) {
      System.out.println("Connection unsuccessful");
      ex.printStackTrace();
      
  }
}
/*This method showTableData() gets the table data from the selected row, and
  inputs it into the text fields so the user can see the data they selected.
*/ 
public void showTableData() {  
     DefaultTableModel  model2 = (DefaultTableModel)jt.getModel();
    int row = jt.getSelectedRow();

    //int col = 0; // ID is the first Column
    textFldProductCode.setText(jt.getValueAt( row, 0 ).toString());
    textFldProductName.setText(jt.getValueAt( row, 1 ).toString());
    textFldBusinessUnit.setText(jt.getValueAt( row, 2 ).toString());
    
         
     }
public void updateData() {
         
 try  (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/salesreporting","root","Tulip");  
        Statement stmt=con.createStatement();)
  { 
       
       String sql = "update products set product_name = '"+textFldProductName.getText()+"', business_unit = '"+textFldBusinessUnit.getText()+"'where product_code = '"+textFldProductCode.getText()+"'  ";
               
        stmt.executeUpdate(sql);
        //con.commit();
       // con.close();
        
            }
         
  catch(Exception ex) {
      System.out.println("Connection unsuccessful");
      ex.printStackTrace();
  }     
     }
 public void deleteData() {
    try  (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/salesreporting","root","Tulip");  
        Statement stmt=con.createStatement();)
  { 
       
       String sql = "delete from products where product_code = '"+textFldProductCode.getText()+"'";
               
        stmt.executeUpdate(sql);
        //con.commit();
       // con.close();
        
            }
         
  catch(Exception ex) {
      System.out.println("Connection unsuccessful");
      ex.printStackTrace();
  } 
}
 public void clearData() {
    textFldProductCode.setText(null);  
    textFldProductName.setText(null);
    textFldBusinessUnit.setText(null);
 }
}//end of class extends